spring:
  application:
    name: sp
  datasource:
    url: jdbc:postgresql://localhost:5432/sp
    username: postgres
    password: sopra*
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  contextPath: /sp
management:
  contextPath: /admin
debug: false